version: '2'
services:
  www:
    build: www
    container_name: surf-screenshotter-www
  worker:
    cap_add:
     - SYS_ADMIN
    image: "tons/surf-screenshotter-worker:0.3"
    build: worker
    container_name: surf-screenshotter-worker

