version: '2'
services:
  www:
    build: www
    container_name: surf-screenshotter-www
  worker:
    build: worker
    container_name: surf-screenshotter-worker
    depends_on:
     - www
    links:
     - www


