version: '3'
services:
  worker:
    cap_add:
      - SYS_ADMIN
    image: "tons/surf-screenshotter-worker:0.6"
    build: .
    container_name: surf-screenshotter-worker
    volumes:
      - "./data_file.txt:/mnt/data/data_file.txt:ro"
