version: '3'
services:
  worker:
    cap_add:
      - SYS_ADMIN
    image: "tons/surf-screenshotter-worker:0.7"
    build: .
    container_name: surf-screenshotter-worker
    volumes:
      - "./data.txt:/mnt/data/data.txt:ro"
      - ./data:/data
